// main.zig — process entry point.
//
// Responsibilities (kept deliberately thin):
//   1. Connect to the Wayland display (the river compositor).
//   2. Walk the global registry and bind the handful of interfaces we need.
//   3. Hand the river globals to the Wm core and run its event loop.
//
// Everything about *window management policy* lives in wm.zig. This file is just
// the plumbing that gets us a live connection.
//
// Background — why this program exists at all:
//   river is a NON-monolithic Wayland compositor. Unlike dwl (compositor + window
//   manager fused into one binary), river is only the compositor. The window
//   manager is a separate client process — this one — that speaks the
//   `river-window-management-v1` protocol. river renders, handles input, talks to
//   the GPU/DRM; we decide layout, focus and borders.

const std = @import("std");
const log = std.log.scoped(.main);

// The "wayland" module is generated by the scanner in build.zig. These namespaces
// mirror the protocol XML:
//   wl    -> core Wayland (wl_compositor, wl_seat, …)
//   river -> our river_* protocols (window manager, xkb bindings, layer shell)
const wayland = @import("wayland");
const wl = wayland.client.wl;
const wp = wayland.client.wp;
const river = wayland.client.river;
const zwlr = wayland.client.zwlr;

const config = @import("config.zig");
const confparse = @import("confparse.zig");
const Context = @import("context.zig");
const wm = @import("wm.zig");
const binding = @import("binding.zig");
const action = @import("action.zig");
const signals = @import("signals.zig");
const ipc = @import("ipc.zig");
const shake = @import("shake.zig");
const seat = @import("seat.zig");
const outputconfig = @import("outputconfig.zig");
const inputconfig = @import("inputconfig.zig");
const gamma = @import("gamma.zig");

// Oldest protocol versions compatible with the requests reach makes today.
// Newer servers are capped to the generated version in registryListener.
const min_rwm_version = 3; // river_seat_v1.pointer_warp
const min_xkb_bindings_version = 2; // river_xkb_bindings_v1.get_seat (chords)

/// The objects we bind from the registry. `core` is what the WM keeps (fields
/// documented on `Context.Globals`); its `rwm` is filled in only after the initial
/// roundtrip confirms the global is present — until then it lives in the optional
/// `rwm` here, since globals arrive asynchronously. The rest go straight to their
/// own modules.
const RegistryGlobals = struct {
    core: Context.Globals = .{ .rwm = undefined },
    rwm: ?*river.WindowManagerV1 = null,
    output_manager: ?*zwlr.OutputManagerV1 = null,
    input_manager: ?*river.InputManagerV1 = null,
    gamma_manager: ?*zwlr.GammaControlManagerV1 = null,
};

extern fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;

pub fn main() !void {
    // Set the process name (/proc/self/comm) to "reach". We're launched through
    // the system dynamic loader (`/lib64/ld-linux-x86-64.so.2 reach`, see run.sh),
    // so without this the kernel-set comm is "ld-linux-x86-64" — which is what
    // fastfetch and `pidof` would otherwise see. PR_SET_NAME = 15.
    _ = std.os.linux.prctl(@intFromEnum(std.os.linux.PR.SET_NAME), @intFromPtr("reach"), 0, 0, 0);

    // We link libc (for libwayland-client), so the C allocator is the simplest,
    // most stable choice and avoids churn in std.heap's debug-allocator naming.
    const gpa = std.heap.c_allocator;

    // 1. Connect. Passing null uses $WAYLAND_DISPLAY. This must be run inside a
    //    river session that is waiting for a window manager to connect.
    const display = try wl.Display.connect(null);
    defer display.disconnect();
    log.info("connected to wayland display", .{});

    // Load the optional runtime config (config.zon) and overlay it onto the
    // compiled-in defaults BEFORE anything reads them — env, monitors, rules,
    // binds and cursor settings are all consumed from here on. No file → defaults
    // stand; a bad file → defaults stand and we log why (never bricks the session).
    confparse.load(gpa);

    // Pin the cursor for X11 children. libXcursor with no XCURSOR_SIZE and no
    // `Xcursor.size` resource falls back to a size derived from the X screen
    // height — on a multi-monitor Xwayland root that is enormous, which is why
    // some X11 windows show a giant pointer. Applied before config.env so an
    // explicit entry there still wins.
    if (config.cursor.export_env) {
        var size_buf: [16]u8 = undefined;
        _ = setenv("XCURSOR_THEME", config.cursor.theme.ptr, 1);
        if (std.fmt.bufPrintZ(&size_buf, "{d}", .{config.cursor.size})) |s| {
            _ = setenv("XCURSOR_SIZE", s.ptr, 1);
        } else |_| {}
    }

    // Export session environment variables (dwl setupenv). Done before anything
    // is spawned so that every child process — autostart, keybinds, and runsvdir
    // user services — inherits the correct Wayland/toolkit env.
    for (config.env) |kv| _ = setenv(kv[0].ptr, kv[1].ptr, 1);

    // 2. Discover globals. getRegistry() asks the server to advertise every
    //    global; each advertisement fires a `.global` event on our listener. A
    //    single roundtrip is enough to receive the initial batch.
    const registry = try display.getRegistry();
    var globals = RegistryGlobals{};
    registry.setListener(*RegistryGlobals, registryListener, &globals);
    if (display.roundtrip() != .SUCCESS) return error.RoundtripFailed;

    // Require the one global we cannot live without. If it is missing, either we
    // are not running under river, or another window manager already claimed it.
    const rwm = globals.rwm orelse {
        log.err("river_window_manager_v1 not found — are we running under river, " ++
            "and is no other WM already connected?", .{});
        return error.MissingWindowManager;
    };

    // Warn (but continue) on the soft dependencies; reach degrades gracefully
    // without them (no borders, no keybindings, as noted per-global).
    if (globals.core.xkb_bindings == null) log.warn("no river_xkb_bindings_v1 — keybindings disabled", .{});
    if (globals.core.layer_shell == null) log.warn("no river_layer_shell_v1 (panels cannot be given a default output)", .{});
    if (globals.core.wp_viewporter == null) log.warn("no wp_viewporter (borders disabled)", .{});
    if (globals.core.wp_single_pixel_buffer_manager == null) log.warn("no wp_single_pixel_buffer_v1 (borders disabled)", .{});

    // 3. Initialise the WM core and run. `init` populates the global context and
    //    attaches the window-manager listener; `run` blocks in the poll loop
    //    until river tells us to stop. `rwm` is now known-present, so the Context
    //    copy takes it non-optional.
    globals.core.rwm = rwm;
    wm.init(gpa, registry, globals.core);

    // SIGHUP → config reload, delivered on the poll loop.
    signals.start();

    // The state socket a panel reads for desktops/focus/titles. reach draws no
    // bar itself, so this is the only way any of that leaves the window manager.
    ipc.start();
    defer ipc.stop();

    // Cursor theme/size, and shake-to-find's pointer devices if enabled.
    seat.cursor_dirty = true;
    shake.start();

    // Output configuration (config.monitors). Applied asynchronously once the
    // compositor advertises heads/modes during the event loop.
    if (globals.output_manager) |om| {
        outputconfig.init(om);
    } else {
        log.warn("no zwlr_output_manager_v1 — monitor config disabled", .{});
    }

    // Gamma: dimming and colour temperature. Registered before the event loop so
    // that every output river announces can be claimed as it arrives; the ramps
    // themselves are written once each output reports its gamma size.
    if (globals.gamma_manager) |gm| {
        gamma.init(gm);
    } else {
        log.warn("no zwlr_gamma_control_manager_v1 — brightness/temperature disabled", .{});
    }

    // Input configuration (keyboard repeat). Applied as devices are announced.
    if (globals.input_manager) |im| {
        inputconfig.init(im);
    } else {
        log.warn("no river_input_manager_v1 — keyboard repeat config disabled", .{});
    }

    // Fire the startup programs (dwl-style autostart) now that we're connected;
    // each runs via `/bin/sh -c` and inherits our WAYLAND_DISPLAY, so it can
    // connect to river.
    for (config.autostart) |cmd| action.spawn(cmd);

    try wm.run(display);
    log.info("clean shutdown", .{});
}

/// Registry listener: binds each advertised global we care about, ignoring the
/// rest. zig-wayland delivers events as a tagged union; `.global` carries the
/// numeric name + interface string + version.
fn registryListener(registry: *wl.Registry, event: wl.Registry.Event, globals: *RegistryGlobals) void {
    switch (event) {
        .global => |g| {
            const c = &globals.core;
            if (is(g, wl.Compositor)) {
                c.wl_compositor = registry.bind(g.name, wl.Compositor, 4) catch return;
            } else if (is(g, wp.Viewporter)) {
                c.wp_viewporter = registry.bind(g.name, wp.Viewporter, 1) catch return;
            } else if (is(g, wp.SinglePixelBufferManagerV1)) {
                c.wp_single_pixel_buffer_manager = registry.bind(g.name, wp.SinglePixelBufferManagerV1, 1) catch return;
            } else if (is(g, river.WindowManagerV1)) {
                if (g.version < min_rwm_version) {
                    log.err("river_window_manager_v1 v{d} advertised; reach requires v{d}+", .{ g.version, min_rwm_version });
                    return;
                }
                globals.rwm = registry.bind(g.name, river.WindowManagerV1, capped(g, river.WindowManagerV1)) catch return;
            } else if (is(g, river.XkbBindingsV1)) {
                if (g.version < min_xkb_bindings_version) {
                    log.warn("river_xkb_bindings_v1 v{d} advertised; reach requires v{d}+", .{ g.version, min_xkb_bindings_version });
                    return;
                }
                c.xkb_bindings = registry.bind(g.name, river.XkbBindingsV1, capped(g, river.XkbBindingsV1)) catch return;
            } else if (is(g, river.LayerShellV1)) {
                c.layer_shell = registry.bind(g.name, river.LayerShellV1, 1) catch return;
            } else if (is(g, zwlr.OutputManagerV1)) {
                globals.output_manager = registry.bind(g.name, zwlr.OutputManagerV1, 1) catch return;
            } else if (is(g, zwlr.GammaControlManagerV1)) {
                globals.gamma_manager = registry.bind(g.name, zwlr.GammaControlManagerV1, 1) catch return;
            } else if (is(g, river.InputManagerV1)) {
                globals.input_manager = registry.bind(g.name, river.InputManagerV1, capped(g, river.InputManagerV1)) catch return;
            }
        },
        // A global went away. We don't track hot-pluggable registry globals, so
        // there is nothing to tear down here.
        .global_remove => {},
    }
}

/// Whether global `g` advertises interface `T`. `orderZ(...) == .eq` is the
/// null-terminated string compare zig-wayland expects here.
fn is(g: anytype, comptime T: type) bool {
    return std.mem.orderZ(u8, g.interface, T.interface.name) == .eq;
}

/// Bind version for `T`: what the server advertises, capped at what we generated.
fn capped(g: anytype, comptime T: type) u32 {
    return @min(g.version, T.generated_version);
}

// `zig test` only collects the tests in the ROOT file, so every test living in
// an imported module — the action, binding and config-parsing ones — silently
// did not run: a deliberately false assertion in any of them still passed.
// Importing a file inside a test block is what pulls its tests into this
// compilation. Add a line here when a new file grows tests.
test {
    _ = @import("action.zig");
    _ = @import("binding.zig");
    _ = @import("config.zig");
    _ = @import("confparse.zig");
    _ = @import("gamma.zig");
    _ = @import("reload.zig");
}
