// main.zig — process entry point.
//
// Responsibilities (kept deliberately thin):
//   1. Connect to the Wayland display (the river compositor).
//   2. Walk the global registry and bind the handful of interfaces we need.
//   3. Hand the river globals to the Wm core and run its event loop.
//
// Everything about *window management policy* lives in wm.zig. This file is just
// the plumbing that gets us a live connection.
//
// Background — why this program exists at all:
//   river is a NON-monolithic Wayland compositor. Unlike dwl (compositor + window
//   manager fused into one binary), river is only the compositor. The window
//   manager is a separate client process — this one — that speaks the
//   `river-window-management-v1` protocol. river renders, handles input, talks to
//   the GPU/DRM; we decide layout, focus, borders, and the bar.

const std = @import("std");
const log = std.log.scoped(.main);

// The "wayland" module is generated by the scanner in build.zig. These namespaces
// mirror the protocol XML:
//   wl    -> core Wayland (wl_compositor, wl_shm, …)
//   river -> our river_* protocols (window manager, xkb bindings, layer shell)
const wayland = @import("wayland");
const wl = wayland.client.wl;
const wp = wayland.client.wp;
const river = wayland.client.river;

const wm = @import("wm.zig");
const bar = @import("bar.zig");
const status = @import("status.zig");
const Font = @import("render/font.zig");

/// Holds the global objects we bind from the registry. Everything is optional
/// because globals arrive asynchronously; after the initial roundtrip we check
/// that the ones we actually require are present.
const Globals = struct {
    // Core Wayland globals. Not strictly needed to merely connect, but we bind
    // them now because borders (M3) and the bar (M4) will create surfaces and
    // shared-memory buffers from them.
    wl_compositor: ?*wl.Compositor = null,
    wl_subcompositor: ?*wl.Subcompositor = null,
    wl_shm: ?*wl.Shm = null,

    // Used by the tmux borders (M3): scale + solid-color buffers.
    wp_viewporter: ?*wp.Viewporter = null,
    wp_single_pixel_buffer_manager: ?*wp.SinglePixelBufferManagerV1 = null,

    // river globals.
    //   window_manager — the protocol that drives this whole program (required).
    //   xkb_bindings   — keyboard bindings (used in M5).
    //   layer_shell    — surfaces for borders/bar (used in M3/M4).
    rwm: ?*river.WindowManagerV1 = null,
    xkb_bindings: ?*river.XkbBindingsV1 = null,
    layer_shell: ?*river.LayerShellV1 = null,
};

pub fn main() !void {
    // We link libc (for libwayland-client), so the C allocator is the simplest,
    // most stable choice and avoids churn in std.heap's debug-allocator naming.
    const gpa = std.heap.c_allocator;

    // 1. Connect. Passing null uses $WAYLAND_DISPLAY. This must be run inside a
    //    river session that is waiting for a window manager to connect.
    const display = try wl.Display.connect(null);
    defer display.disconnect();
    log.info("connected to wayland display", .{});

    // 2. Discover globals. getRegistry() asks the server to advertise every
    //    global; each advertisement fires a `.global` event on our listener. A
    //    single roundtrip is enough to receive the initial batch.
    const registry = try display.getRegistry();
    var globals = Globals{};
    registry.setListener(*Globals, registryListener, &globals);
    if (display.roundtrip() != .SUCCESS) return error.RoundtripFailed;

    // Require the one global we cannot live without. If it is missing, either we
    // are not running under river, or another window manager already claimed it.
    const rwm = globals.rwm orelse {
        log.err("river_window_manager_v1 not found — are we running under river, " ++
            "and is no other WM already connected?", .{});
        return error.MissingWindowManager;
    };

    // Warn (but continue) on the soft dependencies; M1 doesn't use them yet.
    if (globals.wl_shm == null) log.warn("no wl_shm (needed later for the bar)", .{});
    if (globals.layer_shell == null) log.warn("no river_layer_shell_v1 (needed later for the bar)", .{});
    if (globals.xkb_bindings == null) log.warn("no river_xkb_bindings_v1 (needed later for keybinds)", .{});
    if (globals.wp_viewporter == null) log.warn("no wp_viewporter (borders disabled)", .{});
    if (globals.wp_single_pixel_buffer_manager == null) log.warn("no wp_single_pixel_buffer_v1 (borders disabled)", .{});

    // 3. Initialise the WM core and run. `init` populates the global context and
    //    attaches the window-manager listener; `run` blocks in the poll loop
    //    until river tells us to stop.
    wm.init(
        gpa,
        rwm,
        globals.xkb_bindings,
        globals.layer_shell,
        globals.wl_compositor,
        globals.wl_subcompositor,
        globals.wl_shm,
        globals.wp_viewporter,
        globals.wp_single_pixel_buffer_manager,
    );
    defer wm.deinit();

    // M4 bar: initialise the font library, load the configured font, and open
    // the someblocks status fifo. Any failure here just disables the bar (or
    // status); window management still runs.
    Font.initLibrary() catch |err| log.err("fcft init failed: {} — bar disabled", .{err});
    bar.initFont(gpa);
    if (bar.enabled) status.start();

    try wm.run(display);
    log.info("clean shutdown", .{});
}

/// Registry listener: binds each advertised global we care about, ignoring the
/// rest. zig-wayland delivers events as a tagged union; `.global` carries the
/// numeric name + interface string + version.
fn registryListener(registry: *wl.Registry, event: wl.Registry.Event, globals: *Globals) void {
    switch (event) {
        .global => |g| {
            // We compare the advertised interface name against each binding's
            // canonical name. `orderZ(... ) == .eq` is the null-terminated string
            // compare zig-wayland expects here.
            if (std.mem.orderZ(u8, g.interface, wl.Compositor.interface.name) == .eq) {
                globals.wl_compositor = registry.bind(g.name, wl.Compositor, 4) catch return;
            } else if (std.mem.orderZ(u8, g.interface, wl.Subcompositor.interface.name) == .eq) {
                globals.wl_subcompositor = registry.bind(g.name, wl.Subcompositor, 1) catch return;
            } else if (std.mem.orderZ(u8, g.interface, wl.Shm.interface.name) == .eq) {
                globals.wl_shm = registry.bind(g.name, wl.Shm, 1) catch return;
            } else if (std.mem.orderZ(u8, g.interface, wp.Viewporter.interface.name) == .eq) {
                globals.wp_viewporter = registry.bind(g.name, wp.Viewporter, 1) catch return;
            } else if (std.mem.orderZ(u8, g.interface, wp.SinglePixelBufferManagerV1.interface.name) == .eq) {
                globals.wp_single_pixel_buffer_manager = registry.bind(g.name, wp.SinglePixelBufferManagerV1, 1) catch return;
            } else if (std.mem.orderZ(u8, g.interface, river.WindowManagerV1.interface.name) == .eq) {
                globals.rwm = registry.bind(g.name, river.WindowManagerV1, 4) catch return;
            } else if (std.mem.orderZ(u8, g.interface, river.XkbBindingsV1.interface.name) == .eq) {
                globals.xkb_bindings = registry.bind(g.name, river.XkbBindingsV1, 2) catch return;
            } else if (std.mem.orderZ(u8, g.interface, river.LayerShellV1.interface.name) == .eq) {
                globals.layer_shell = registry.bind(g.name, river.LayerShellV1, 1) catch return;
            }
        },
        // A global went away. We don't bind anything hot-pluggable at M1, so there
        // is nothing to tear down here yet.
        .global_remove => {},
    }
}
